# Generated by Django 6.0 on 2025-12-28 11:10
#
# This migration creates the initial database tables
# for the "books" app. It defines:
# - the Book model (global book catalogue)
# - the UserBook model (user-specific reading library)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

     # Marks this as the first migration for the app
    initial = True

    # This migration depends on Django's user model,
    # because UserBook has a ForeignKey to the authenticated user
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Database operations performed by this migration
    operations = [
        # Create the Book model
        migrations.CreateModel(
            name='Book',
            fields=[
                # Primary key (automatically generated)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Core book metadata
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                # Classification fields used for recommendations
                ('goal', models.CharField(choices=[('focus', 'Focus'), ('sleep', 'Sleep'), ('fitness', 'Fitness'), ('mindset', 'Mindset'), ('productivity', 'Productivity'), ('stress', 'Stress')], max_length=20)),
                ('mood', models.CharField(choices=[('motivated', 'Motivated'), ('tired', 'Tired'), ('overwhelmed', 'Overwhelmed'), ('curious', 'Curious'), ('calm', 'Calm')], max_length=20)),
                # Estimated daily reading time (used for time-based recommendations)
                ('minutes_per_day', models.IntegerField(default=10)),
                # Optional tag field for future extensions or filtering
                ('tags', models.CharField(blank=True, max_length=300)),
            ],
        ),
        # Create the UserBook model
        migrations.CreateModel(
            name='UserBook',
            fields=[
                # Primary key
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Reading status for the user
                ('status', models.CharField(choices=[('want', 'Want to read'), ('reading', 'Reading'), ('finished', 'Finished')], default='want', max_length=20)),
                # Timestamp when the book was saved to the user's library
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                # Optional user feedback
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                # Relations to Book and User
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                # Ensure a user can only save the same book once
                'unique_together': {('user', 'book')},
            },
        ),
    ]