# Generated by Django 6.0 on 2025-12-28 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(choices=[('focus', 'Focus'), ('sleep', 'Sleep'), ('fitness', 'Fitness'), ('mindset', 'Mindset'), ('productivity', 'Productivity'), ('stress', 'Stress')], max_length=20)),
                ('mood', models.CharField(choices=[('motivated', 'Motivated'), ('tired', 'Tired'), ('overwhelmed', 'Overwhelmed'), ('curious', 'Curious'), ('calm', 'Calm')], max_length=20)),
                ('minutes_per_day', models.IntegerField(default=10)),
                ('tags', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want', 'Want to read'), ('reading', 'Reading'), ('finished', 'Finished')], default='want', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
