# Generated by Django 6.0 on 2025-12-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
