# Generated by Django 6.0 on 2025-12-28 21:33
#
# This migration extends the UserBook model by adding
# a progress field, allowing users to track how far
# they are in reading a book (in percentage).

from django.db import migrations, models


class Migration(migrations.Migration):
    # This migration depends on the initial books app migration,
    # ensuring the UserBook model already exists
    dependencies = [
        ('books', '0001_initial'),
    ]
    # Database operations performed by this migration
    operations = [
        migrations.AddField(
            model_name='userbook',
            name='progress',

            # Integer field storing reading progress (0–100)
            # Default is 0, meaning not started yet
            field=models.IntegerField(default=0),
        ),
    ]