# Generated by Django 6.0 on 2025-12-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_userbook_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
