# Generated by Django 6.0 on 2025-12-28 22:58
#
# This migration adds an "updated_at" timestamp to the UserBook model.
# It allows the application to track when a user last modified
# their reading state (progress, notes, rating, or status).

from django.db import migrations, models


class Migration(migrations.Migration):
    
    # This migration depends on the previous UserBook migration
    # that introduced the progress field
    dependencies = [
        ('books', '0002_userbook_progress'),
    ]

    # Database operations performed by this migration
    operations = [
        migrations.AddField(
            model_name='userbook',
            name='updated_at',

            # Automatically updates the timestamp every time
            # the UserBook record is modified
            field=models.DateTimeField(auto_now=True),
        ),
    ]