# Generated by Django 6.0 on 2025-12-27 10:55
#
# This migration file was automatically generated by Django.
# It introduces the Streak model, which tracks consecutive
# completion behavior for habits.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the Streak model.

    This migration creates the database table used to store
    streak information for habits, including the current
    streak count and the date of the last completed habit.
    """

    # Marks this as the first migration for the streaks app
    initial = True

    # This migration depends on the HabitCheckIn model
    # from the habits app, since streaks are conceptually
    # linked to existing habits.
    dependencies = [
        ("habits", "0002_habitcheckin"),
    ]

    # Operations applied when running this migration
    operations = [
        migrations.CreateModel(
            name="Streak",
            fields=[
                # Primary key automatically created by Django
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                # Number of consecutive days the habit was completed
                ("count", models.PositiveIntegerField(default=0)),

                # Date when the habit was last completed
                # Used to determine whether a streak continues or resets
                ("last_completed", models.DateField(blank=True, null=True)),

                # One-to-one relationship with a Habit
                # Each habit can have at most one associated streak
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
