# Generated by Django 6.0 on 2025-12-27 15:42
#
# This migration extends the existing Streak model
# by adding a field to track the longest streak
# ever achieved for a habit.

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to extend the Streak model with a longest_streak field.

    This field stores the maximum number of consecutive days
    a habit has ever been completed, independent of the current streak.
    """

    # This migration depends on the initial creation
    # of the Streak model.
    dependencies = [
        ("streaks", "0001_initial"),
    ]

    # Operations applied when running this migration
    operations = [
        migrations.AddField(
            model_name="streak",
            name="longest_streak",
            # Stores the maximum streak length reached so far
            field=models.PositiveIntegerField(default=0),
        ),
    ]
