# Generated by Django 6.0 on 2025-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streak",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
