# Generated by Django 6.0 on 2025-12-22 12:54
#
# This migration creates the initial Habit model.
# It defines the database table used to store
# basic habit information.

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the Habit model.

    This migration introduces the core Habit table,
    which stores user-defined habits along with
    their creation timestamp.
    """

    # Marks this as the first migration for the habits app
    initial = True

    # No dependencies, as this is the first model
    # created within the habits app.
    dependencies = [
    ]

    # Operations applied when running this migration
    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                # Primary key automatically generated by Django
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID"
                    ),
                ),

                # Name of the habit (user-defined)
                ("name", models.CharField(max_length=100)),

                # Timestamp of when the habit was created
                # Automatically set when the habit is first saved
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
