# Generated by Django 6.0 on 2025-12-22 16:03
#
# This migration introduces the HabitCheckIn model.
# It stores daily completion records for habits
# and serves as the historical basis for streak calculations.

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to create the HabitCheckIn model.

    HabitCheckIn represents a daily record indicating whether
    a specific habit was completed on a given date.
    This model enables tracking habit history over time.
    """

    # This migration depends on the initial creation
    # of the Habit model.
    dependencies = [
        ("habits", "0001_initial"),
    ]

    # Operations applied when running this migration
    operations = [
        migrations.CreateModel(
            name="HabitCheckIn",
            fields=[
                # Primary key automatically generated by Django
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID"
                    ),
                ),

                # Date of the habit check-in
                # Defaults to the current date
                ("date", models.DateField(default=datetime.date.today)),

                # Indicates whether the habit was completed on this date
                ("completed", models.BooleanField(default=True)),

                # Foreign key linking the check-in to a habit
                # Deleting a habit removes all associated check-ins
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit"
                    ),
                ),
            ],

            # Ensures that each habit can only have
            # one check-in per date
            options={
                "unique_together": {("habit", "date")},
            },
        ),
    ]
