# Generated by Django 6.0 on 2025-12-27 15:27
#
# This migration modifies the Habit model by adjusting
# the default value of the created_at field.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to update the default value of the Habit.created_at field.

    This change ensures that the creation timestamp is explicitly
    set using Django's timezone-aware `now()` function, improving
    consistency with timezone settings.
    """

    # This migration depends on the creation of the HabitCheckIn model
    # within the habits app.
    dependencies = [
        ("habits", "0002_habitcheckin"),
    ]

    # Operations applied when running this migration
    operations = [
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            # Use a timezone-aware timestamp instead of auto_now_add
            field=models.DateTimeField(
                default=django.utils.timezone.now
            ),
        ),
    ]
