# Generated by Django 6.0 on 2025-12-27 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habitcheckin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
