# Generated by Django 6.0 on 2025-12-29 11:52
# Initial database migration for the Pomodoro feature.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Marks this as the first migration for the pomodoro app
    initial = True

    # Dependencies ensure required tables exist before this migration runs
    dependencies = [
        ('habits', '0003_alter_habit_created_at'),
        # Link pomodoro sessions to Django's user model
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create the PomodoroSession model/table
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                # Primary key (auto-generated)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Length of the pomodoro session in minutes
                ('duration_minutes', models.PositiveIntegerField(default=25)),
                # Timestamp when the session starts
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                # Timestamp when the session ends (nullable if still running)
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                # Current state of the session (running / completed / stopped)
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='running', max_length=20)),
                # Timestamp when the record was created
                ('created_at', models.DateTimeField(auto_now_add=True)),
                # Optional link to a habit (session may be general focus)
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                # The user who owns the pomodoro session
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]