# Generated by Django 6.0 on 2025-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosession',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
