# Generated by Django 6.0 on 2025-12-30 14:13
# Migration to adjust pomodoro session duration handling.
from django.db import migrations, models


class Migration(migrations.Migration):

    # This migration depends on the initial PomodoroSession model
    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        # Remove the duration stored in minutes
        # (no longer needed for the timer implementation)
        migrations.RemoveField(
            model_name='pomodorosession',
            name='duration_minutes',
        ),
        # Add duration stored in seconds (default = 25 minutes)
        # This simplifies countdown calculations in JavaScript
        migrations.AddField(
            model_name='pomodorosession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]