# Generated by Django 6.0 on 2025-12-27 19:22
#
# This migration file was automatically generated by Django.
# It defines the initial database schema for the Todo model.
# Migrations are used to keep the database structure in sync
# with changes made to models.py.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the Todo model.

    This migration creates the database table that stores
    Todo items, including their title, completion status,
    and creation timestamp.
    """

    # Marks this as the first migration for this app
    initial = True

    # No dependencies, since this is the initial migration
    dependencies = []

    # List of operations applied when running this migration
    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                # Primary key (automatically generated by Django)
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                # Short text describing the task
                ("title", models.CharField(max_length=200)),

                # Boolean flag indicating whether the task is completed
                ("is_done", models.BooleanField(default=False)),

                # Timestamp when the todo item was created
                # Defaults to the current time at creation
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
